credentials:
  usernames:
    admin:
      email: logiservices2000@gmail.com
      name: Arminio
      password: Arminio  # Genera dopo

cookie:
  name: invoicepro
  key: logiservices2000
  expiry_days: 180

preauthorized:
  emails: []
