credentials:
  usernames:
    user1:
      email: logiservices2000@gmail.com
      name: "Arminio"
      password: "Arminio"  # hashed password

cookie:
  name: invoice_pro
  key: 112358
  expiry_days: 10000
  # ‚Üê RIMUOVI sezione preauthorized completamente
