credentials:
  usernames:
    user1:
      email: logiservices2000@gmail.com
      name: Arminio
      password: "Arminio"  # hashed password

cookie:
  name: invoice_pro
  key: some_signature_key_32_chars_long_like_this_123456
  expiry_days: 10000
  # ‚Üê RIMUOVI sezione preauthorized completamente
